name: emrobostack-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
#   - /home/tobias/mambaforge/envs/emrobostack-dev/conda-bld/
  - https://repo.mamba.pm/robostack-wasm
dependencies:
  - numpy
  - matplotlib
  - ipycanvas
  - ipywidgets
  - jupyterlab_widgets
  - ros-humble-osrf-testing-tools-cpp
  - ros-humble-rcutils
  - ros-humble-rclpy
  - ros-humble-rosidl-parser
  - ros-humble-std-msgs
  - ros-humble-wasm-cpp
  - ros-humble-rmw-wasm-cpp
